version: 1.0.{build}

image: Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf true
  - cmd: git config --global core.symlinks true

install:
- git submodule update --init --recursive

build_script:
  - bin\build.cmd test

notifications:
  - provider: Email
    to:
      - belt@santoslab.org
    on_build_success: false
    
