version: 1.0.{build}

image: Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf true
  - cmd: git config --global core.symlinks true

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64
  PATH: 'C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%'
  SIREUM_SOURCE_BUILD: true

cache:
  - sireum\bin\win\java
  - sireum\bin\scala

build_script:
  - bash -lc "pacman --noconfirm -S unzip zip"
  - bash -lc "rm -rf $APPVEYOR_BUILD_FOLDER/out $APPVEYOR_BUILD_FOLDER/versions.properties"
  - IF EXIST %USERPROFILE%\.mill RD /S /Q %USERPROFILE%\.mill
  - git submodule update --init --recursive
  - bash -lc "$APPVEYOR_BUILD_FOLDER/bin/test.sh"
  - bin\act.bat

notifications:
  - provider: Email
    to:
      - belt@santoslab.org
    on_build_success: false
    