language: none

services:

build:
  pre_ci:
  pre_ci_boot:
    image_name: sireum/kekinian
    image_tag: latest
    pull: true
    options: "-e HOME=/root"
  ci:
  - >
    if [[ ! `git show -s HEAD | grep -F -q "[skip shippable]"` ]]; then
      git submodule update --init --recursive &&
      export SIREUM_SOURCE_BUILD=true &&
      rm -fR out ~/.mill versions.properties &&
      bin/test.sh &&
      bin/act;
    fi
  post_ci:
  on_success:
  on_failure:
  push:
  cache: true
  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/sireum/bin/java
    - $SHIPPABLE_BUILD_DIR/sireum/bin/scala

integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - belt@santoslab.org
      sendConsoleLogs: true
