os: osx

osx_image: xcode9.4

script:
- if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis]" ; then echo "skip travis" && exit 0 ; fi
- if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[travis skip]" ; then echo "travis skip" && exit 0 ; fi
- export SIREUM_SOURCE_BUILD=true
- bin/test.sh
- bin/act