os: osx

osx_image: xcode10.1

addons:
  homebrew:
    packages:
      - p7zip

script:
- if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis]" ; then echo "skip travis" && exit 0 ; fi
- if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[travis skip]" ; then echo "travis skip" && exit 0 ; fi
- git submodule update --init --recursive
- export SIREUM_SOURCE_BUILD=true
- rm -fr out ~/.mill versions.properties
- bin/build.cmd build
- bin/act

notifications:
  email:
    recipients:
      - belt@santoslab.org
    on_success: never
    on_failure: always
